### ISSUE TITLE
missing sensor(s) on update

### ISSUE THREAD

**Issue by bsp9493** [briis/meteobridge#11]
Hi...

question/issue...  I used to be able to pull my indoor temperature and humidity from the data logger.

I'm guessing these are gone?  is there any chance at replacing them?

**Comment by briis** [comment]
Did you upgrade to V3.0.0?
And yes inside values can come back. Good to know that someone uses them.

**Comment by bsp9493** [comment]
yes, just upgraded this morning, and noticed as I was reworking the name changes into my lovelace displays.

good to know:)  

Thanx!

**Comment by briis** [comment]
3.0.1 is out which adds these two sensors back.
I did leave out some sensors that was there before (and introduced new ones), so let me know if there are other values you need.

Closing this issue.

**Comment by bsp9493** [comment]
Thank you!!

d
