### ISSUE TITLE
sea level and station pressure inverted

### ISSUE THREAD

**Issue by bsp9493** [briis/meteobridge#12]
unless I am misunderstanding or my configuration has been wrong for years, it looks like sea level and station pressures are inverted with this release

I would expect 
sea level = absolute pressure
station = relative pressure

**Comment by briis** [comment]
Let me check in the morning.

**Comment by bsp9493** [comment]
no worries...
just something I noticed with the new update, I had to switch, actually now that I look closer at it, I'm not sure - might just be my interpretation.

from sensors created by integration
Meteobridge Station Pressure - 966.6 hPa
Meteobridge Sea Level Pressure - 1,017.1 hPa

from meteobridge
pressure | 966.6mb |
sealevel pressure | 1017.1mb |

from my station
Absolute Pressure |  966.6
Relative Pressure |  1017.10

**Comment by briis** [comment]
I double checked. And the values reported are correct. Sea Level pressure will almost always be higher than station pressure - unless you live on the beach.

I also checked values with a second weather station I have, and this one reports the values in the same way. So I am sure the current values are correct.

So I will close this now.

**Comment by bsp9493** [comment]
Thanx for confirming!!!

d
