### ISSUE TITLE
Extra sensors.

### ISSUE THREAD

**Issue by livefeed** [briis/meteobridge#15]
Hello thank you for working on this. I have a few extra senses mainly temperature and soil temp that show up on my metrobridge anyway to include them in your output?

**Comment by briis** [comment]
Yes there is. There is already support for some extra sensors. (Up to 7). If you go to the Integrations page and find the Meteobridge integration, then click on the CONFIGURE text in the lower left corner. Here you can move the slider for extra sensors. Move to the number of extra Temp sensors you have and they should show up - I hope. I cannot test this as I don't have any extra sensors. Please let me know the result of that - what sensors are you getting?

Then go to your Meteobridge interface and click *Station* and *Mapping*, take a screen dump and post it here for me to see the Physical and Logical sensor names.

**Comment by livefeed** [comment]
<img width="708" alt="Screen Shot 2021-11-24 at 1 52 06 PM" src="https://user-images.githubusercontent.com/5816636/143297535-bb501bae-4883-49d5-b2db-510229cd625b.png">

**Comment by briis** [comment]
Thanks. So you have 4 soil sensors and 2 leaf sensors installed?
These will not show up when activating the extra sensors as they are different types.

I could add them manually, but I am trying to work with the developer of Meteobridge to see if I could extract a list of all the logical sensors, and then build the sensors that match what people have installed.

**Comment by livefeed** [comment]
Correct, if it is something that could be added that would be fantastic. Thank you for your help.

**Comment by briis** [comment]
Could you copy the below, change the. USERNAME, PASSWORD and IP_ADDRESS to your values, and then execute that in a Browser and post the results here. I just need to ensure what comes out.

`http://USERNAME:PASSWORD@IP_ADDRESS/cgi-bin/template.cgi?template=[soil0temp-act:None];[soil0hum-act:None];[soil1temp-act:None];[soil1hum-act:None];[soil2temp-act:None];[soil2hum-act:None];[soil3temp-act:None];[soil3hum-act:None];[leaf0temp-act:None];[leaf0hum-act:None];[leaf1temp-act:None];[leaf1hum-act:None]`

**Comment by briis** [comment]
@livefeed I have released v3.1.0, which should create the Soil and Leaf sensors for you. As I cannot test it myself, I hope you can give it a run, and let me know how this goes.
When looking at the Meteobridge documentation, it is a bit unclear what value the Humidity sensor returns, so current I assume it is a number, but let me know what it shows so I can adjust the Unit of Measurement if needed.

**Comment by livefeed** [comment]
Sorry for not getting back to you. Installed 3.1.0 and my sensors are showing up!! Very happy and thank you for do this.

>

**Comment by briis** [comment]
Very good. Closing the issue.
