### ISSUE TITLE
Missing montly and yearly precipitation sensors after updating to 3.x

### ISSUE THREAD

**Issue by tiba222** [briis/meteobridge#19]
Hi,

After the upgrade from 2.6.3 to 3.2.2 I am missing sensors showing the year and month precipitation totals as available in 2.6.3, only the daily precipitation total is still available in 3.2.2 (sensor.meteobridge_precipitation_today). Is it possible to add these sensors showing the monthly and yearly precipitation total again?

Thanks for the good work!

Regards,
Tim

**Comment by briis** [comment]
Sure. I will add them back.

**Comment by briis** [comment]
Released 3.2.2, which has added the two missing sensors.

**Comment by tiba222** [comment]
Thanks for the very quick fix!
