### ISSUE TITLE
Feature Request : integrated weather component

### ISSUE THREAD

**Issue by xannor** [briis/meteobridge#2]
This is something I had built when I was tooling around with accessing my GW1000, it is a "generic" weather component that can use both darksky (or another weather component) and injects weather data from the gw1000. This could give you a foundation to build something similar for the metobridge, injecting sensor data where/when available.

https://github.com/xannor/hass_gw1000/blob/master/custom_components/gw1000/weather.py

this is handy since there is no weather template.

**Comment by briis** [comment]
Thanks @xannor. My plan was NOT to add the Weather component to this, as it varies a lot what people want to use, especially since the announcement around DarkSky. 
But this generic template might make it interesting again. 
I will look in to this when I have time. Thanks.

**Comment by xannor** [comment]
Well, I got inspired this morning and I created this: https://github.com/xannor/hass_weather_template
so you can close this if you do not want to build your own.

**Comment by briis** [comment]
Very cool, so with this you can actually mix and match live data from a Personal Weather Station, with Forecast data from a Weather Provider. I like it.

**Comment by briis** [comment]
I will link to your component, and not build my own. Thanks.
