### ISSUE TITLE
Wind Chill not correct

### ISSUE THREAD

**Issue by lightmaster** [briis/meteobridge#20]
Meteobridge shows that Wind Chill is currently 38.1F, whereas this HACS addon is showing 59.4F. The addon's value is changing as Meteobridge's value changes, but the addon's value is consistently higher than it should be.

**Comment by briis** [comment]
Wind Chill was until now a Calculated value, as Meteobridge had issues with WeatherFlow stations and Wind Chill calculations. The December 6th release of Meteobridge have fixed that problem, so I can now revert to use the wind_chill value from the Meteobridge station. So you should now see the same value on your Meteobridge station as you see in this Integration. 
I have released V3.2.4 where this fix is included.
