### ISSUE TITLE
Language files german

### ISSUE THREAD

**Issue by rogerkilo** [briis/meteobridge#22]

**Comment by rogerkilo** [comment]
[German.zip](https://github.com/briis/meteobridge/files/8357544/German.zip)

Both "sensor.de.json" and "de.json" attached in zip-file.

**Comment by briis** [comment]
You can make a pull request based on a Fork of this Repo. But let me just merge them for now. THANKS.

**Comment by briis** [comment]
Just released 3.2.5 version, which contains your language files.
