### ISSUE TITLE
Feature Request: Override default units

### ISSUE THREAD

**Issue by lightmaster** [briis/meteobridge#4]
Title says it all. Would be nice to be able to override the default units. While it did choose the right temperature degrees for me, pressure is using inHg instead of mb/hPa.

**Comment by briis** [comment]
I will do this as soon as I have time. Plan is to let the user pick the Display unit for the different unit types when configuring the Integration. This might be a breaking change, requiring to delete and re-add.

**Comment by lightmaster** [comment]
Looks like it's working good, at least as far as using `MB` instead of `in/Hg`
