### ISSUE TITLE
Extend the number of extra sensors

### ISSUE THREAD

**Issue by ongenal** [briis/meteobridge#6]
in the current implementation the extra sensors are limited to 2.  The Meteobridge PRO >4.4 supports now secondary stations like a cheap GW1000 (Ecowitt) or DP1500 (Froggit) where you can add multiple sensors in a cheap way, but I can't get them in HA.

**Comment by briis** [comment]
I have not tried this, but I assume these sensors are just added with an incremented number like th3temp, th4 temp etc. Is that correct?
If yes, how many extra sensors do you need? And for what type of sensors?

**Comment by ongenal** [comment]
Indeed, the additional sensor in my case are temperature / humidity sensor and  are th3temp, th3hum,  … till th7temp, th7hum.  ( I use 4 at this moment, metobrigde spports 7). Typical also dewpoint is available also,   and battery status. thXbat,   I don’t use dewpoint,  battery status can be nice, but no absolute need)

All supported by the sensormapping feature in the metobridge.

Luc

**Comment by briis** [comment]
I will look at it as fast as I can.

**Comment by ongenal** [comment]
Would be nice,   not urgent for me,   I found a work around that partial solved my problem
Luc

**Comment by NIghtHawkATL** [comment]
I also would like to add on to this request for absolute pressure. the weather station I have (ambient weather 1401-IP has an RF sensor for indoor temp, humidity and absolute pressure and the only thing that the integration does not provide right now is the Absolute pressure.
![Screen Shot 2021-04-30 at 12 05 12 PM](https://user-images.githubusercontent.com/8395658/116722603-9b4e4880-a9ac-11eb-9e01-54f53e84426c.png)

**Comment by briis** [comment]
I have just released v2.6.3 which should fix both of the requested features. Closing this now.
