### ISSUE TITLE
no reinstallation possible

### ISSUE THREAD

**Issue by legi1** [briis/meteobridge#7]
I had to reinstall the Integration. But now it is in the HACS Integration but not on the integration page in the settings anymore? The files are on their place and I did it twice. Any hint?

**Comment by briis** [comment]
When you are on the Integration page, try and do a Hard Refresh of your browser, and it should show up again

**Comment by legi1** [comment]
thanks that worked, should have know that, sorry

**Comment by briis** [comment]
No problem. Glad it works.
