### ISSUE TITLE
No time of measuring at high and low temp.sensors

### ISSUE THREAD

**Issue by Waling1961** [briis/meteobridge#8]
As already indicated via HACommunity, I would like the measured time as an extra attribute for the following sensors:
- sensor.temp_high_today (only time)
- sensor.temp_low_today   (only time)
- sensor.temp_month_max
- sensor.temp_month_min
- sensor.temp_year_max
- sensor.temp_year_min

**Comment by briis** [comment]
Sorry for this looooong delay. The Integration has now been rewritten, and it is now much easier to change things. So in the V3.0.0 I have implemented your request above.
