### ISSUE TITLE
do not see in config>integations page

### ISSUE THREAD

**Issue by infragilis** [briis/meteobridge#9]
where do i add the ip/user/pass ?
i have 2.6.3 installed via HACS, i see the folders in custom_components
that's where i get lost or miss something. (reinstalled/restarted multiple times)

HACS 1.13.2
Home Assistant 2021.7.3

**Comment by infragilis** [comment]
upgraded to latest version of HA/all the way .. it works now

**Comment by briis** [comment]
Glad to hear, and sorry for the delay, I have been on vacation. 
If it happens again, you just need to do a Hard Refresh, when on the Integrations Page in HA. It is a caching issue in the browser. I will close it now.
